version: '2.1'

references:
  workspace_root: &workspace_root ~/

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  version_regex: &version_regex /^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.\d+)?$/

  version_tags_only: &version_tags_only
    tags:
      only: *version_regex

  non_tagged_only: &non_tagged_only
    tags:
      ignore: *version_regex

  cache_key: &cache_key cache-{{ checksum "./package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *cache_key
      paths:
        - ./node_modules/

jobs:
  install:
    docker:
      - image: cimg/node:18.6.0
    resource_class: medium
    steps:
      - checkout

      - *restore_node_modules

      - run:
          name: Install Dependencies
          command: npm install

      - *cache_node_modules

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test:
    docker:
      - image: cimg/node:18.6.0
    resource_class: medium
    steps:
      - *attach_workspace

      - run:
          name: Run Code Tests
          command: npm run test

  build:
    docker:
      - image: cimg/node:18.6.0
    resource_class: medium
    steps:
      - *attach_workspace

      - run:
          name: Build Application
          command: npm run build

  docker-build:
    docker:
      - image: cimg/base:2022.10
    resource_class: medium
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: docker build . -t $IMAGE_NAME:$CIRCLE_TAG

workflows:
  test-build-deploy:
    jobs:
      - install:
          filters: *version_tags_only
      - test:
          requires:
            - install
          filters: *version_tags_only
      - build:
          requires:
            - test
          filters: *non_tagged_only
      - docker-build:
          requires:
            - test
          filters:
            <<: *version_tags_only
            branches:
              ignore: /.*/
